name: Daily LeetCode

on:
  schedule:
    - cron: '0 1 * * *'   # 每天早上 09:00 台灣時間
  workflow_dispatch:

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install requests

      - name: 推送每日一題
        run: python send_leetcode.py
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          MODE: "daily"

      - name: 推送指定難度題目
        run: python send_leetcode.py
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL_RANDOM }}
          MODE: "random"
          DIFFICULTY: "EASY"   # ← 要換難度改這裡
